# Generated by Django 2.2.17 on 2021-01-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='music_posts_blog',
        ),
    ]
